// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knxgxpbsqxhlcrjzdlir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtueGd4cGJzcXhobGNyanpkbGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzAxMzAsImV4cCI6MjA3MzcwNjEzMH0.UXHMhaELfzLyw8LFkYV_hIdDqhcI4kfvbyYLFYEWs90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});